### PR TITLE
Fix labeller ignoring non-defined sync-labels option and ignoring .lock.hcl glob

### PR DESCRIPTION
**Pull request by jakemulley**
This PR _should_ fix the following issues:

- PRs that include `**.lock.hcl` file changes not being appropriately tagged as `dependencies` ([example](https://github.com/ministryofjustice/modernisation-platform/pull/316/files))
- Labeler ignoring sync-labels being unset or explicitly "false" due to the way ECMAScript uses the variable ([more info](https://github.com/actions/labeler/issues/104)), by now explicitly setting an empty variable. This should fix the issue where manually tagged PRs lose their labels when labeler runs ([example](https://github.com/ministryofjustice/modernisation-platform/pull/320#event-4296370480))

### CODE REVIEW

**Comment by jakemulley** [comment]
The reason this PR had the `dependencies` label [removed](https://github.com/ministryofjustice/modernisation-platform/pull/321#event-4296522204) is because it uses the base ref workflow, rather than the updated workflow in this PR.

**Comment by Jasstkn** [comment]
@jakemulley could you tell when this PR will be merged to main?

**Comment by jakemulley** [comment]
@Jasstkn It'll likely be merged today into [ministryofjustice/modernisation-platform](https://github.com/ministryofjustice/modernisation-platform) 👍🏼

**Review by zuriguardiola — APPROVED** [review]

**Review by philhorrocks — COMMENTED** [review]
all good

**Pull request merged**
