### PR TITLE
Fix's implemeneted

### PR DESCRIPTION
**Pull request by markgov**
This Code fixes all this issues that i have found to do with the SCA. SCA should now complete with a green tick

### CODE REVIEW

**Comment by dms1981** [comment]
Hi @markgov - the most recent run still appears to have a number of failed checks in the Static Code Analysis step. Did you still have changes to make before this PR gets reviewed / approved?

**Review by davidkelliott — DISMISSED** [review]
LGTM!

**Review by dms1981 — CHANGES_REQUESTED** [review]
Can you be a bit more descriptive with the skip reasons please?

**Review by dms1981 — APPROVED** [review]
LGTM

**Pull request merged**
