### PR TITLE
Update team.html.md.erb

### PR DESCRIPTION
**Pull request by ep-93**
.. my first PR ever on this account.

### CODE REVIEW

**Review by dms1981 — APPROVED** [review]
LGTM!

**Review by jakemulley — COMMENTED** [review]
You’ll be the 10th team member, do you want to update the count at the top? 🎉

**Review by dms1981 — DISMISSED** [review]
Still LGTM - but if you wanted to, you could remove `Christine Elliott, Business Analyst` and drop the team count back down to 9 members 😄

**Comment by ep-93** [comment]
I'll remove Christine Elliott, Business Analyst , and sort my permissions out hopefully so I can squash and merge this PR.

**Review by dms1981 — APPROVED** [review]
LGTM again!

**Pull request merged**
