### PR TITLE
Update policy for cicd-member-policy

### PR DESCRIPTION
**Pull request by georgepstaylor**
Update the ci-cd member policy:

- We need to be able to deploy services/tasks to ECS Fargate.
- We need to be able to look up a secret value

### CODE REVIEW

**Review by davidkelliott — CHANGES_REQUESTED** [review]
Hi @georgepstaylor , thanks for raising this, this policy by other application teams as well so please can nothing be removed (eg. codepipeline lines have been removed).  It should be fine to add the additional permissions you need, but could you not reorder them as it makes it hard to see what has been added! Thanks :)

**Comment by georgepstaylor** [comment]
> Hi @georgepstaylor , thanks for raising this, this policy by other application teams as well so please can nothing be removed (eg. codepipeline lines have been removed). It should be fine to add the additional permissions you need, but could you not reorder them as it makes it hard to see what has been added! Thanks :)

Thanks,  @davidkelliott - I have re structured the file and the diff now shows a much cleaner picture of the changes.

**Review by adeweetman-al — APPROVED** [review]
👍

**Review by davidkelliott — APPROVED** [review]
👍 thanks!

**Pull request merged**
