### PR TITLE
push core-vpc account files

### PR DESCRIPTION
**Pull request by donmasters**

### CODE REVIEW

**Review by philhorrocks — APPROVED** [review]
all good

**Comment by philhorrocks** [comment]
look

**Comment by andy3267** [comment]
I dont work for the MOJ. Remove me from your system
    On Tuesday, 15 December 2020, 13:26:04 GMT, donmasters <notifications@github.com> wrote:  
 
 
You can view, comment on, or merge this pull request online at:

  https://github.com/ministryofjustice/modernisation-platform/pull/193

Commit Summary
   
   - push core-vpc account files

File Changes
   
   -  A terraform/environments/core-vpc/backend.tf (48) 
   -  A terraform/environments/core-vpc/secrets.tf (11) 

Patch Links:
   
   - https://github.com/ministryofjustice/modernisation-platform/pull/193.patch
   - https://github.com/ministryofjustice/modernisation-platform/pull/193.diff

**Comment by jakemulley** [comment]
Hi @andy3267,

Thanks for getting in touch. We're unsure how you came to get these notifications, but we can't subscribe people to our repositories on GitHub, and nor can we unsubscribe them. You'll need to unsubscribe yourself, which you can do by clicking "unsubscribe" in the bottom of your notification email, or you can go to your [GitHub watching settings](https://github.com/watching) to see an overview of everything you're subscribed to.

Let me know if that works,
Jake

**Pull request merged**
