### PR TITLE
Add workflow to automate module documentation

### PR DESCRIPTION
**Pull request by zuriguardiola**
And add READMEs to modules that did not have them

### CODE REVIEW

**Review by adeweetman-al — COMMENTED** [review]
Looks great Zuri, just wondered if you'd considered a way around hard-coding the module names in the workflow? Are there technical/process reasons for doing so?

**Comment by zuriguardiola** [comment]
> Looks great Zuri, just wondered if you'd considered a way around hard-coding the module names in the workflow? Are there technical/process reasons for doing so?

Updated the workflow to use find-dir configuration to automatically find READMEs within the given directory.

**Comment by adeweetman-al** [comment]
> > Looks great Zuri, just wondered if you'd considered a way around hard-coding the module names in the workflow? Are there technical/process reasons for doing so?
> 
> Updated the workflow to use find-dir configuration to automatically find READMEs within the given directory.

Nice one. Could you use this for the terraform module path triggers as well, again to avoid the specific mod names?
/terraform/modules/*/**.md

**Review by adeweetman-al — APPROVED** [review]
Looks good. Nice work.

**Pull request merged**
